<?php

use PHPCensor\Helper\Lang;
use PHPCensor\Model\Build;
use PHPCensor\Store\EnvironmentStore;
use PHPCensor\Store\Factory;

/**
 * @var Build[] $builds
 */

?>

<?php if (empty($builds) || !count($builds)): ?>
    <tr class="">
        <td colspan="10"><?= Lang::get('no_builds_yet'); ?></td>
    </tr>
<?php endif; ?>

<?php foreach ($builds as $build): ?>

<?php
switch ($build->getStatus()) {
    case 0:
        $cls      = 'active';
        $subClass = 'info';
        $status   = Lang::get('pending');

    break;

    case 1:
        $cls      = 'warning';
        $subClass = 'warning';
        $status   = Lang::get('running');
    break;

    case 2:
        $cls      = 'success';
        $subClass = 'success';
        $status   = Lang::get('success');
    break;

    case 3:
        $cls      = 'danger';
        $subClass = 'danger';
        $status   = Lang::get('failed');
    break;
}

$branches = $build->getExtra('branches');
?>
<tr>
    <td><a href="<?= APP_URL ?>build/view/<?= $build->getId(); ?>">#<?= str_pad($build->getId(), 6, '0', STR_PAD_LEFT); ?></a></td>
    <td><span class='label label-<?= $subClass ?>'><?= $status ?></span></td>
    <td><?= $build->getCreateDate()->format('Y-m-d H:i:s'); ?></td>
    <td><?= $build->getSourceHumanize(); ?></td>
    <td class="hidden-md hidden-sm hidden-xs">
        <?php
            if (!empty($build->getCommitId())) {
                print sprintf(
                    '<a href="%s">%s %s</a>',
                    $build->getCommitLink(),
                    substr($build->getCommitId(), 0, 7),
                    $build->getCommitterEmail() ? ('(' . $build->getCommitterEmail() . ')') : ''
                );
            } else {
                print '&mdash;';
            }
        ?>
    </td>
    <td>
        <?php if (in_array($build->getSource(), Build::$pullRequestSources, true)): ?>
            <a href="<?= $build->getRemoteBranchLink(); ?>">
                <i class="fa fa-code-fork"></i>
                <?= $build->getRemoteBranch(); ?> :
            </a>
        <?php endif; ?>
        <a href="<?= $build->getBranchLink(); ?>">
            <i class="fa fa-code-fork"></i>
            <?= $build->getBranch(); ?>
        </a>
        <?= $branches ? ' + '.implode(', ', $branches) : ''; ?>
        <?php if ($tag = $build->getTag()): ?> /
             <a href="<?= $build->getTagLink(); ?>">
                <i class="fa fa-tag"></i>
                 <?= $tag; ?>
            </a>
        <?php endif; ?>
    </td>
    <td>
        <?php
            $environmentId = $build->getEnvironmentId();
            $environment   = null;
            if ($environmentId) {
                /** @var EnvironmentStore $environmentStore */
                $environmentStore  = Factory::getStore('Environment');
                $environmentObject = $environmentStore->getById($environmentId);
                if ($environmentObject) {
                    $environment = $environmentObject->getName();
                }
            }

            echo !empty($environment) ? $environment : '—' ;
        ?>
    </td>
    <td>
        <?= $build->getDuration(); ?> <?= Lang::get('seconds'); ?>
    </td>
    <td>
        <?= (int)$build->getErrorsTotal(); ?>
        <?php if (!in_array($build->getStatus(), [Build::STATUS_PENDING, Build::STATUS_RUNNING], true)): ?>
            <?php $trend = $build->getErrorsTrend(); ?>
            <?php if (1 === $trend): ?>
                <i class="fa fa-arrow-down arrow_trend_positive"></i>
            <?php elseif (-1 === $trend): ?>
                <i class="fa fa-arrow-up arrow_trend_negative"></i>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <td>
        <?= $build->getErrorsNew(); ?>
    </td>
    <td>
        <div class="btn-group btn-group-right">
            <a class="btn btn-default btn-sm" href="<?= APP_URL; ?>build/view/<?= $build->getId(); ?>"><?= Lang::get('view'); ?></a>
            <?php if ($this->getUser()->getIsAdmin()): ?>
            <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="<?= APP_URL; ?>build/delete/<?= $build->getId(); ?>" class="delete-build"><?= Lang::get('delete_build'); ?></a></li>
            </ul>
            <?php endif; ?>
        </div>
    </td>
</tr>
<?php endforeach; ?>

<script>
    $(document).ready(function() {
        $('.delete-build').on('click', function (e) {
            e.preventDefault();
            confirmDelete(e.target.href)
                .onCloseConfirmed = function () {window.location = window.location.href};
        });
    });
</script>
