build_settings:
    ignore:
        - vendor
        - tests

setup:
    composer:
        action: install
    env:
        SKIP_DB_TESTS: '0'
        POSTGRESQL_USER: '%SECRET:postgres_testdb_user%'
        POSTGRESQL_PASSWORD: '%SECRET:postgres_testdb_password%'
        POSTGRESQL_DBNAME: '%SECRET:postgres_testdb_name%_%BUILD_ID%'
    shell:
        execute_all: true
        commands:
            - "cd ~ && ./create_test_ci_postgres_db.sh %BUILD_ID%"

test:
    php_unit:
        config:
            - phpunit.xml.dist
        coverage: true

    php_cs_fixer:
        args: '--allow-risky=yes'
        errors: true
        report_errors: true
        config: .php-cs-fixer.dist.php
        allow_failures: true

    php_cpd:
        allow_failures: true
        ignore:
            - 'src/Languages'

    php_loc:
        allow_failures: true

    php_parallel_lint:
        allow_failures: true

    security_checker:
        binary_type:    symfony
        allow_failures: false

complete:
    shell:
        commands:
            - "cd ~ && ./drop_test_ci_postgres_db.sh %BUILD_ID%"
    email_notify:
        default_mailto_address: poisoncorpsee@gmail.com
    telegram_notify:
        auth_token: "%SECRET:telegram_auth_token%"
        recipients:
            - "%SECRET:telegram_chat_id%"
        send_log: false
