build_settings:
  clone_depth: 1
  ignore:
    - vendor
    - tests

setup:
  composer:
    action: install

test:
  php_unit:
    config:
      - phpunit.xml

  php_mess_detector:
    allow_failures: true
    rules:
      - phpmd.xml

  php_code_sniffer:
    standard:       PSR2
    encoding:       UTF-8
    allow_failures: true

  php_cpd:
    allow_failures: true

  php_loc:
    allow_failures: true

  php_parallel_lint:
    allow_failures: true

  php_docblock_checker:
    allow_failures: true

  security_checker:
    allow_failures: false

complete:
  email:
    default_mailto_address: poisoncorpsee@gmail.com
