build_settings:
  ignore:
    - vendor
    - tests

setup:
  composer:
    action: install

test:
  php_unit:
    config:
      - phpunit.xml
    coverage: coverage

  php_mess_detector:
    allow_failures: true

  php_code_sniffer:
    standard:       PSR2
    encoding:       UTF-8
    allow_failures: true

  php_cpd:
    allow_failures: true

  php_loc:
    allow_failures: true

  php_parallel_lint:
    allow_failures: true

  php_docblock_checker:
    allow_failures: true

failure:
  email:
    committer: true

complete:
  email:
    default_mailto_address: poisoncorpsee@gmail.com
