build_settings:
    ignore:
        - vendor
        - tests

setup:
    composer:
        action: install

test:
    php_unit:
        config:
            - phpunit.xml.dist
        coverage: true

    php_code_sniffer:
        standard:       PSR2
        encoding:       UTF-8
        allow_failures: true
        ignore:
            - src/Migrations

    php_cpd:
        allow_failures: true

    php_loc:
        allow_failures: true

    php_parallel_lint:
        allow_failures: true

#    security_checker:
#        allow_failures: false

complete:
    email_notify:
        default_mailto_address: poisoncorpsee@gmail.com
