<?php

use PHPCensor\Helper\Lang;
use PHPCensor\Model\Build;
use PHPCensor\Model\Project;

/**
 * @var array     $builds
 * @var Project[] $projects
 * @var Build     $lastBuild
 */

foreach ($projects as $project):
    $statuses        = [];
    $failures        = 0;
    $backgroundClass = 'gray';
    $success         = null;
    $failure         = null;

    if (\count($builds[$project->getId()])) {
        // Get the most recent build status to determine the main block colour.
        $lastBuild = $builds[$project->getId()][0];
        $status = $lastBuild->getStatus();

        switch ($status) {
            case Build::STATUS_PENDING:
                $backgroundClass = 'blue';
                break;
            case Build::STATUS_RUNNING:
                $backgroundClass = 'yellow';
                break;
            case Build::STATUS_SUCCESS:
                $backgroundClass = 'green';
                break;
            case Build::STATUS_FAILED:
                $backgroundClass = 'red';
                break;
        }
        // Use the last 5 builds to determine project health:
        $failures = 0;

        /** @var Build $build */
        foreach ($builds[$project->getId()] as $build) {
            switch ($build->getStatus()) {
                case Build::STATUS_PENDING:
                    $statuses[] = 'pending';
                    break;
                case Build::STATUS_RUNNING:
                    $statuses[] = 'running';
                    break;
                case Build::STATUS_SUCCESS:
                    $statuses[] = 'ok';
                    $success = \is_null($success) && !\is_null($build->getFinishDate()) ? $build->getFinishDate()->format('Y-m-d H:i:s') : $success;
                    break;
                case Build::STATUS_FAILED:
                    $failures++;
                    $statuses[] = 'failed';
                    $failure = \is_null($failure) && !\is_null($build->getFinishDate()) ? $build->getFinishDate()->format('Y-m-d H:i:s') : $failure;
                    break;
            }
        }
    }

    $buildCount  = \count($builds[$project->getId()]);
    $lastSuccess = $successful[$project->getId()];
    $lastFailure = $failed[$project->getId()];
    $message     = Lang::get('no_builds_yet');

    if ($buildCount > 0) {
        if ($failures > 0) {
            $message = Lang::get('x_of_x_failed', $failures, $buildCount);

            if (!\is_null($lastSuccess) && !\is_null($lastSuccess->getFinishDate())) {
                $message .= Lang::get('last_successful_build', $lastSuccess->getFinishDate()->format('Y-m-d H:i:s'));
            } else {
                $message .= Lang::get('never_built_successfully');
            }
        } else {
            $message = Lang::get('all_builds_passed', $buildCount);

            if (!\is_null($lastFailure) && !\is_null($lastFailure->getFinishDate())) {
                $message .= Lang::get('last_failed_build', $lastFailure->getFinishDate()->format('Y-m-d H:i:s'));
            } else {
                $message .= Lang::get('never_failed_build');
            }
        }
    }

?>
    <div class="project-box" id="project-box-<?= $project->getId(); ?>" style="overflow: hidden; word-wrap: anywhere;">
    <div class="small-box small-box-full bg-<?= $backgroundClass; ?>">

        <div class="inner">
            <h3 class="dashboard-box-title">
                <a href="<?= APP_URL; ?>project/view/<?= $project->getId(); ?>">
                    <?= $project->getTitle(); ?>
                </a>
            </h3>

            <p>
                <?= $message; ?>
            </p>

        </div>
        <div class="icon">
            <i class="fa fa-<?= $project->getIcon(); ?>"></i>
        </div>
        <a href="<?= APP_URL; ?>project/view/<?= $project->getId(); ?>" class="small-box-footer small-box-footer-project">
            <div class="pull-left" style="margin-left: 10px">
                <?php if ($project->getAllowPublicStatus()): ?>
                    <i class="fa fa-unlock"></i>
                <?php else: ?>
                    <i class="fa fa-lock"></i>
                <?php endif; ?>
            </div>
            <?= Lang::get('view_project'); ?> (<?= $counts[$project->getId()]; ?>) <i class="fa fa-arrow-circle-right"></i>
        </a>

        <?php
            for ($idx = 0; $idx < 5; $idx++) {
                if (empty($builds[$project->getId()][$idx])) {
                    echo '<span class="small-box-footer-build small-box-footer bg-gray"><i class="fa fa-minus"></i></span>';
                } else {
                    $build = $builds[$project->getId()][$idx];
                    $link = APP_URL . 'build/view/' . $build->getId();

                    switch ($build->getStatus()) {
                        case Build::STATUS_PENDING:
                            $class = 'bg-blue';
                            $icon = 'fa-clock-o blink-item';
                            break;
                        case BUild::STATUS_RUNNING:
                            $class = 'bg-yellow';
                            $icon = 'fa-cogs blink-item';
                            break;
                        case Build::STATUS_SUCCESS:
                            $class = 'bg-green';
                            $icon = 'fa-check';
                            break;
                        case BUild::STATUS_FAILED:
                            $class = 'bg-red';
                            $icon = 'fa-times';
                            break;
                    }

                    echo '<a href="' . $link .'" class="small-box-footer-build small-box-footer ' . $class . '"><i class="fa ' . $icon . '"></i></a>';
                }
            }
        ?>
        <div style="clear: both;"></div>
    </div>
    </div>

<?php endforeach; ?>
