<?php

use PHPCensor\Helper\Lang;

?>
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><?= Lang::get('latest_builds'); ?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body" id="timeline-box">
        <?= $timeline ?>
    </div>
</div>
