<?php

use PHPCensor\Helper\Lang;
use PHPCensor\Helper\Template;
use PHPCensor\Model\Build;
use PHPCensor\Store\EnvironmentStore;

/**
 * @var Build[]          $builds
 * @var EnvironmentStore $environmentStore
 */

?>
<ul class="timeline">
    <?php $last = new DateTime('-1 Year'); ?>

    <?php
    foreach ($builds as $build):
        $environmentId = $build->getEnvironmentId();
        $environment   = null;
        if ($environmentId) {
            $environmentObject = $environmentStore->getById($environmentId);
            if ($environmentObject) {
                $environment = $environmentObject->getName();
            }
        }

        $branches = $build->getExtra('branches');

        switch ($build->getStatus()) {
            case Build::STATUS_PENDING:
                $updated = $build->getCreateDate();
                $label = Lang::get('pending');
                $color = 'blue blink-item';
                break;

            case Build::STATUS_RUNNING:
                $updated = $build->getStartDate();
                $label = Lang::get('running');
                $color = 'yellow blink-item';
                break;

            case Build::STATUS_SUCCESS:
                $updated = $build->getFinishDate();
                $label = Lang::get('success');
                $color = 'green';
                break;

            case Build::STATUS_FAILED:
                $updated = $build->getFinishDate();
                $label = Lang::get('failed');
                $color = 'red';
                break;
        }

        if (!$updated) {
            $updated = $build->getCreateDate();
        }

        if ($updated->format('Y-m-d') != $last->format('Y-m-d')): $last = $updated;
            ?>
            <li class="time-label">
    <span class="bg-gray">
        <?= $last->format('Y-m-d'); ?>
    </span>
            </li>
        <?php endif; ?>

        <!-- /.timeline-label -->
        <!-- timeline item -->
        <li>
            <i class="fa fa-<?= $build->getProject()->getIcon(); ?> bg-<?= $color; ?>"></i>
            <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i>
                <?php
                    echo $updated->format('H:i:s');
                    if ($build->getStatus() != Build::STATUS_PENDING) {
                        echo ' &mdash; ' . $build->getDuration(); ?> <?= Lang::get('seconds');
                    }
                ?>
                </span>
                <h3 class="timeline-header">
                    <a href="<?= APP_URL; ?>build/view/<?= $build->getId(); ?>">
                        #<?= $build->getId(); ?>
                    </a>
                    &mdash;
                    <a href="<?= APP_URL; ?>project/view/<?= $build->getProjectId(); ?>">
                        <?= $build->getProject()->getTitle(); ?>
                    </a>
                    <?php if ($environment): ?>
                        &mdash;
                        <i class="fa fa-gear"></i>
                        <span style="color: #999"><?= $environment; ?></span>
                    <?php endif; ?>
                </h3>

                <div class="timeline-body">
                    <p>
                    <?= $build->getSourceHumanize(); ?> &mdash;
                    <?php if (\in_array($build->getSource(), Build::$pullRequestSources, true)): ?>
                        <a href="<?= $build->getRemoteBranchLink(); ?>">
                            <i class="fa fa-code-fork"></i>
                            <?= $build->getRemoteBranch(); ?> :
                        </a>
                    <?php endif; ?>

                    <a href="<?= $build->getBranchLink(); ?>">
                        <i class="fa fa-code-fork"></i>
                        <?= $build->getBranch(); ?>
                    </a>
                    <?= $branches ? ' + ' . \implode(', ', $branches) : ''; ?>
                    <?php if ($tag = $build->getTag()): ?> /
                        <a href="<?= $build->getTagLink(); ?>">
                            <i class="fa fa-tag"></i>
                            <?= $tag; ?>
                        </a>
                    <?php endif; ?>
                    <?php
                        if (!empty($build->getCommitId())) {
                            echo ' &mdash; ';
                            echo \sprintf(
                                '<a href="%s">%s %s</a>',
                                $build->getCommitLink(),
                                substr($build->getCommitId(), 0, 7),
                                $build->getCommitterEmail() ? ('(' . $build->getCommitterEmail() . ')') : ''
                            );
                            $buildCommitMessage = Template::clean($build->getCommitMessage());
                            if ($buildCommitMessage) {
                                echo ' &mdash; ';
                                echo $buildCommitMessage;
                            }
                        }
                    ?>
                    </p>
                    <?php if (!\in_array($build->getStatus(), [Build::STATUS_PENDING, Build::STATUS_RUNNING], true)): ?>
                        <p style="color: #999">
                            <?= Lang::get('total_errors'); ?>:
                            <?php if (!\in_array($build->getStatus(), [Build::STATUS_PENDING, Build::STATUS_RUNNING], true)): ?>
                                <?php $trend = $build->getErrorsTrend(); ?>
                                <?php if (1 === $trend['trend']): ?>
                                    <span class="arrow_trend_positive"><?= (int)$build->getErrorsTotal(); ?> (<?= $trend['delta']; ?>)</span><i class="fa fa-arrow-down arrow_trend_positive"></i>
                                <?php elseif (-1 === $trend['trend']): ?>
                                    <span class="arrow_trend_negative"><?= (int)$build->getErrorsTotal(); ?> (+<?= $trend['delta']; ?>)</span><i class="fa fa-arrow-up arrow_trend_negative"></i>
                                <?php else: ?>
                                    <?= (int)$build->getErrorsTotal(); ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($newErrorsCount = $build->getErrorsNew()): ?>
                                /
                                <?= Lang::get('new_errors'); ?>:
                                <?= $newErrorsCount; ?>
                            <?php endif; ?>

                            |
                            <?= Lang::get('test_coverage'); ?>:
                            <?php if (!\in_array($build->getStatus(), [Build::STATUS_PENDING, Build::STATUS_RUNNING], true)): ?>
                                <?php $trend = $build->getTestCoverageTrend(); ?>
                                <?php if (-1 === $trend['trend']): ?>
                                    <span class="arrow_trend_positive"><?= $build->getTestCoverage(); ?>% (+<?= $trend['delta']; ?>%)</span><i class="fa fa-arrow-up arrow_trend_positive"></i>
                                <?php elseif (1 === $trend['trend']): ?>
                                    <span class="arrow_trend_negative"><?= $build->getTestCoverage(); ?>% (<?= $trend['delta']; ?>%)</span><i class="fa fa-arrow-down arrow_trend_negative"></i>
                                <?php else: ?>
                                    <?= $build->getTestCoverage(); ?>%
                                <?php endif; ?>
                            <?php endif; ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </li>
        <!-- END timeline item -->

    <?php endforeach; ?>

    <li>
        <i class="fa fa-clock-o"></i>
    </li>
</ul>
