<div id="<?= $id; ?>" class="control-group <?= $containerClass; ?>">
    <?php if ($label): ?>
        <label class="control-label"><?= $label; ?></label>
    <?php endif; ?>
    <div class="controls">
        <?php foreach ($options as $val => $lbl): ?>
            <label class="radio" for="radio-<?= $id; ?>-<?= $val; ?>">
                <input type="radio" id="radio-<?= $id; ?>-<?= $val; ?>" class="<?= $class; ?>"
                    name="<?= $name; ?>"
                    value="<?= $val; ?>"
                    <?= ($value == $val) ? ' checked="checked"' : ''; ?> <?= $required ? 'required' : '' ?>
                >
                <?= $lbl; ?>
            </label>
        <?php endforeach; ?>

        <?php if (isset($error)): ?>
            <span class="help-block"><?= $error; ?></span>
        <?php endif; ?>
    </div>
</div>
