<div class="control-group <?= $containerClass; ?> <?= (isset($error) ? 'error' : ''); ?>">
    <?php if ($label): ?>
        <label class="control-label" for="<?= $id ?>"><?= $label; ?></label>
    <?php endif; ?>

    <div class="controls">
        <input id="<?= $id; ?>" type="<?= $type; ?>" class="<?= $class; ?>"
            name="<?= $name; ?>"
            <?= isset($value) ? ' value="' . $value . '"' : '' ?>
            <?= isset($pattern) ? ' pattern="' . $pattern . '"' : '' ?>
            <?= $required ? ' required' : '' ?>
        >
        <?php if (isset($error)): ?>
            <span class="help-block"><?= $error; ?></span>
        <?php endif; ?>
    </div>
</div>
