<div class="control-group <?= $containerClass; ?>">
    <?php if ($label): ?>
        <label class="control-label" for="<?= $id ?>"><?= $label; ?></label>
    <?php endif; ?>

    <div class="controls">
        <select id="<?= $id; ?>" class="<?= $class; ?>" name="<?= $name; ?>">
            <?php foreach ($options as $val => $lbl): ?>
                <option
                    value="<?= $val; ?>" <?= ($value == $val) ? ' selected="selected"' : ''; ?>
                ><?= $lbl; ?></option>
            <?php endforeach; ?>
        </select>

        <?php if (isset($error)): ?>
            <span class="help-block"><?= $error; ?></span>
        <?php endif; ?>
    </div>
</div>
