<div class="control-group <?= $containerClass; ?> <?= (isset($error) ? 'error' : ''); ?>">
    <?php if ($label): ?>
        <label class="control-label" for="<?= $id ?>"><?= $label; ?></label>
    <?php endif; ?>
    <div class="controls">
        <textarea rows="<?= $rows; ?>" id="<?= $id; ?>" class="<?= $class; ?>"
                  name="<?= $name; ?>" <?= $required ? ' required' : '' ?>><?= isset($value) ? $value : '' ?></textarea>

        <?php if (isset($error)): ?>
            <span class="help-block"><?= $error; ?></span>
        <?php endif; ?>
    </div>
</div>
