<?php foreach ($groups as $group): ?>
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><?php print $group['title']; ?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <?php print $group['summary']; ?>
    </div>
</div>
<?php endforeach; ?>
