<?php

use PHPCensor\Model\User;

/**
 * @var $exception Exception
 */

/** @var User $user */
$user = $this->getUser();

?>
<div class="panel panel-danger">
    <div class="box-header">
        <h2 class="box-title">Sorry, there was a problem</h2>
    </div>


        <div class="box-body">
            <strong>Message</strong>: <?= $exception->getMessage(); ?><br />
            <strong>File</strong>: <?= $exception->getFile(); ?><br />
            <strong>Line</strong>: <?= $exception->getLine(); ?><br />
            <strong>Trace</strong>:
            <pre style="white-space: pre-wrap"><?= $exception->getTraceAsString(); ?></pre>
        </div>

</div>
