<!DOCTYPE html>
<html>
    <head>
        <title><?php print $project->getTitle(); ?> - PHP Censor</title>

        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <link href="<?php print APP_URL; ?>assets/vendor/admin-lte/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php print APP_URL; ?>assets/vendor/admin-lte/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php print APP_URL; ?>assets/vendor/admin-lte/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
        <link href="<?php print APP_URL; ?>assets/vendor/admin-lte/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
        <link href="<?php print APP_URL; ?>assets/css/ansi-colors.css" rel="stylesheet" type="text/css" />
        <link href="<?php print APP_URL; ?>assets/css/main.css" rel="stylesheet" type="text/css" />

        <link href="<?php print APP_URL; ?>assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php print APP_URL; ?>assets/vendor/ion-icons/css/ionicons.min.css" rel="stylesheet" type="text/css" />

        <script src="<?php print APP_URL; ?>assets/vendor/admin-lte/plugins/jQuery/jquery-2.2.3.min.js"></script>
        <script src="<?php print APP_URL; ?>assets/js/class.js"></script>
        <script src="<?php print APP_URL; ?>assets/vendor/sprintf-js/dist/sprintf.min.js"></script>
        <script src="<?php print APP_URL; ?>assets/vendor/moment/min/moment-with-locales.min.js"></script>
        <script src="<?php print APP_URL; ?>assets/js/app.js" type="text/javascript"></script>
    </head>
    <body class="hold-transition skin-black layout-top-nav">
    <div class="wrapper">
        <header class="main-header">
            <nav class="navbar navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <a href="<?php print APP_URL; ?>" class="logo" style="background-color: #222d32; text-align: left;">PHP Censor</a>
                    </div>
                </div>
            </nav>
        </header>
        <div class="content-wrapper">
            <div class="container">
                <section class="content">
                    <?php if (!empty($latest)): ?>

                        <?php

                        $statusClass = null;
                        $statusText = null;

                        switch ($latest->getStatus()) {
                            case 0:
                                $statusClass = 'blue';
                                $statusText = 'Pending';
                                break;
                            case 1:
                                $statusClass = 'yellow';
                                $statusText = 'Running';
                                break;
                            case 2:
                                $statusClass = 'green';
                                $statusText = 'Success';
                                break;
                            case 3:
                                $statusClass = 'red';
                                $statusText = 'Failed';
                                break;
                        }

                        ?>

                        <div class="small-box small-box-full bg-<?= $statusClass; ?>">
                            <div class="inner">
                                <h3 class="box-title">
                                    <?php print $latest->getProject()->getTitle(); ?> #<?php print $latest->getId(); ?> (<?= $statusText; ?>)
                                </h3>
                                <p>
                                    <?php if ($latest->getCommitMessage()): ?>
                                        <?php print $latest->getCommitMessage(); ?><br /><br />
                                    <?php endif; ?>
    
                                    <strong>Branch: </strong> <?php print $latest->getBranch(); ?><br />
                                    <strong>Committer: </strong> <?php print $latest->getCommitterEmail(); ?>
    
                                    <?php if ($latest->getCommitId() != 'Manual'): ?>
                                        <br /><strong>Commit: </strong> <?php print $latest->getCommitId(); ?><br>
                                    <?php endif; ?>
                                </p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-<?php print $project->getIcon(); ?>"></i>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                    <?php endif; ?>

                    <div class="box">
                        <div class="box-header"><h3 class="box-title">Builds</h3></div>
                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Commit</th>
                                <th>Branch</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody id="latest-builds">


                            <?php if(empty($builds) || !count($builds)): ?>
                                <tr class="">
                                    <td colspan="6">No builds yet.</td>
                                </tr>
                            <?php endif; ?>

                            <?php foreach($builds as $build): ?>

                                <?php
                                switch($build->getStatus())
                                {
                                    case 0:
                                        $class  = 'info';
                                        $status = 'Pending';

                                        break;

                                    case 1:
                                        $class  = 'warning';
                                        $status = 'Running';
                                        break;

                                    case 2:
                                        $class  = 'success';
                                        $status = 'Success';
                                        break;

                                    case 3:
                                        $class  = 'danger';
                                        $status = 'Failed';
                                        break;
                                }
                                ?>
                                <tr>
                                    <td>#<?php print str_pad($build->getId(), 6, '0', STR_PAD_LEFT); ?></td>

                                    <td>
                                        <?php
                                        if ($build->getCommitId() !== 'Manual') {
                                            print '<a href="' . $build->getCommitLink() . '">';
                                        }
                                        print $build->getCommitId();
                                        if ($build->getCommitId() !== 'Manual') {
                                            print '</a>';
                                        }
                                        ?>
                                    </td>

                                    <td><a href="<?php print $build->getBranchLink(); ?>"><?php print $build->getBranch(); ?></a></td>
                                    <td>
                                        <span class='label label-<?php echo $class ?>'><?php echo $status ?></span>
                                    </td>
                                </tr>
                            <?php endforeach; ?>


                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
        <!--<footer class="main-footer">
            <div class="container">
            </div>
        </footer>-->
    </div>
    </body>
</html>
