<?php

use PHPCensor\Helper\Lang;

$user = $this->getUser();

?>
<div class="clearfix"  style="margin-bottom: 20px;">
    <div class="pull-right btn-group">
        <a class="btn btn-success" href="<?= APP_URL; ?>user/add"><?= Lang::get('add_user'); ?></a>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th><?= Lang::get('email_address'); ?></th>
                        <th><?= Lang::get('name'); ?></th>
                        <th><?= Lang::get('is_admin'); ?></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody id="users">
                    <?php foreach($users['items'] as $user): ?>
                        <?php
                        switch($user->getIsAdmin())
                        {
                            case 0:
                                $cls = '';
                                $status = Lang::get('no');
                                break;

                            case 1:
                                $cls = 'warning';
                                $status = Lang::get('yes');
                                break;
                        }
                        ?>
                        <tr class="<?= $cls; ?>">
                            <td><a href="<?= APP_URL; ?>user/edit/<?= $user->getId(); ?>"><?= $user->getEmail(); ?></a></td>
                            <td><?= htmlspecialchars($user->getName()); ?></td>
                            <td><?= $status; ?></td>
                            <td>
                                <?php if($user->getIsAdmin()): ?>
                                    <div class="btn-group btn-group-right">
                                        <a class="btn btn-default btn-sm" href="<?= APP_URL; ?>user/edit/<?= $user->getId(); ?>"><?= Lang::get('edit'); ?></a>
                                        <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?= APP_URL; ?>user/delete/<?= $user->getId(); ?>" class="delete-user"><?= Lang::get('delete_user'); ?></a></li>
                                        </ul>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
         </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.delete-user').on('click', function (e) {
            e.preventDefault();
            confirmDelete(e.target.href)
                .onCloseConfirmed = function () {window.location = window.location.href};
        });
    });
</script>
