<?php use PHPCensor\Helper\Lang; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php Lang::out('log_in_to_app'); ?></title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="<?php print APP_URL; ?>assets/vendor/admin-lte/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php print APP_URL; ?>assets/css/login.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="container">
    <div class="row">
        <a id="logo" href="/">
            <img src="<?php print APP_URL; ?>assets/img/php-censor-white.svg" alt="PHP Censor" width="290" height="auto" /><br />
        </a>
        <div class="" id="login-box">
            <?php print $content; ?>
        </div>
    </div>
</div>

<script src="<?php print APP_URL; ?>assets/vendor/admin-lte/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="<?php print APP_URL; ?>assets/vendor/admin-lte/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

</body>
</html>
