<?php
use PHPCensor\Helper\Lang;

$statuses = [];
$failures = 0;
$subcls   = 'gray';
$cls      = '';
$success  = null;
$failure  = null;

if (count($builds)) {
    // Get the most recent build status to determine the main block colour.
    $last_build = $builds[0];
    $status = $last_build->getStatus();
    switch($status) {
        case 0:
            $subcls = 'blue';
            break;
        case 1:
            $subcls = 'yellow';
            break;
        case 2:
            $subcls = 'green';
            break;
        case 3:
            $subcls = 'red';
            break;
    }
    // Use the last 5 builds to determine project health:
    $failures = 0;

    foreach ($builds as $build) {
        switch ($build->getStatus()) {
            case 0:
                $statuses[] = 'pending';
                break;
            case 1:
                $statuses[] = 'running';
                break;
            case 2:
                $statuses[] = 'ok';
                $success = is_null($success) && !is_null($build->getFinished()) ? $build->getFinished()->format('Y-m-d H:i:s') : $success;
                break;
            case 3:
                $failures++;
                $statuses[] = 'failed';
                $failure = is_null($failure) && !is_null($build->getFinished()) ? $build->getFinished()->format('Y-m-d H:i:s') : $failure;
                break;
        }
    }
}

$buildCount  = count($builds);
$lastSuccess = $successful;
$lastFailure = $failed;
$message = Lang::get('no_builds_yet');
$shortMessage = Lang::get('no_builds_yet');

if ($buildCount > 0) {
    if ($failures > 0) {
        $shortMessage = Lang::get('x_of_x_failed_short', $failures, $buildCount);
        $message = Lang::get('x_of_x_failed', $failures, $buildCount);

        if (!is_null($lastSuccess) && !is_null($lastSuccess->getFinished())) {
            $message .= Lang::get('last_successful_build', $lastSuccess->getFinished()->format('Y-m-d H:i:s'));
        } else {
            $message .= Lang::get('never_built_successfully');
        }
    } else {
        $message = Lang::get('all_builds_passed', $buildCount);
        $shortMessage = Lang::get('all_builds_passed_short', $buildCount, $buildCount);

        if (!is_null($lastFailure) && !is_null($lastFailure->getFinished())) {
            $message .= Lang::get('last_failed_build', $lastFailure->getFinished()->format('Y-m-d H:i:s'));
        } else {
            $message .= Lang::get('never_failed_build');
        }
    }
}

?>

<div class="small-box small-box-full bg-<?php print $subcls; ?>">
    
    <div class="inner">
        <h3>
            <a href="<?php print APP_URL; ?>project/view/<?php print $project->getId(); ?>">
                <?php print $project->getTitle(); ?>
            </a>
        </h3>

        <p>
            <?php print $message; ?>
        </p>

    </div>
    <div class="icon">
        <i class="fa fa-<?php print $project->getIcon(); ?>"></i>
    </div>
    <a href="<?php print APP_URL; ?>project/view/<?php print $project->getId(); ?>" class="small-box-footer small-box-footer-project">
        <?php Lang::out('view_project'); ?> (<?php print $counts; ?>) <i class="fa fa-arrow-circle-right"></i>
    </a>

        <?php for ($idx=0; $idx < 5; $idx++) {
        if (empty($builds[$idx])) {
            echo '<span class="small-box-footer-build small-box-footer bg-gray"><i class="fa fa-minus"></i></span>';
        } else {
            $build = $builds[$idx];
            $link = APP_URL . 'build/view/' . $build->id;
            switch ($build->getStatus()) {
                case 0:
                    $class = 'bg-blue';
                    $icon = 'fa-clock-o';
                    break;
                case 1:
                    $class = 'bg-yellow';
                    $icon = 'fa-cogs';
                    break;
                case 2:
                    $class = 'bg-green';
                    $icon = 'fa-check';
                    break;
                case 3:
                    $class = 'bg-red';
                    $icon = 'fa-times';
                    break;
            }
            echo '<a href="' . $link .'" class="small-box-footer-build small-box-footer ' . $class . '"><i class="fa ' . $icon . '"></i></a>';
        }
    } ?>
    <div style="clear: both;"></div>
</div>
