<?php

use PHPCensor\Helper\Lang;
use PHPCensor\Model\Build;

?>
<script>
    var DASHBOARD = true;
</script>
<div class="row">

    <div class="col-sm-5">
        <?php foreach ($groups as $group): ?>
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?php print $group['title']; ?></h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">
                <?php print $group['summary']; ?>
            </div>
        </div>
        <?php endforeach; ?>
    </div>

    <div class="col-sm-7 pull-left">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?php Lang::out('latest_builds'); ?></h3>
            </div>

            <div class="box-body" id="timeline-box">
                <ul class="timeline">
                    <?php $last = new \DateTime('-1 Year'); ?>

                    <?php
                    foreach ($builds as $build):
                        $environment = $build->getEnvironment();
                        $branches = $build->getExtra('branches');

                        switch ($build->getStatus()) {
                            case Build::STATUS_PENDING:
                                $updated = $build->getCreated();
                                $label = Lang::get('pending');
                                $color = 'blue';
                                break;

                            case Build::STATUS_RUNNING:
                                $updated = $build->getStarted();
                                $label = Lang::get('running');
                                $color = 'yellow';
                                break;

                            case Build::STATUS_SUCCESS:
                                $updated = $build->getFinished();
                                $label = Lang::get('success');
                                $color = 'green';
                                break;

                            case Build::STATUS_FAILED:
                                $updated = $build->getFinished();
                                $label = Lang::get('failed');
                                $color = 'red';
                                break;
                        }

                        if (!$updated) {
                            $updated = $build->getCreated();
                        }

                        if ($updated->format('Y-m-d') != $last->format('Y-m-d')): $last = $updated;
                            ?>
                            <li class="time-label">
                                <span class="bg-gray">
                                <?= $last->format('Y-m-d'); ?>
                                </span>
                            </li>
                        <?php endif; ?>

                        <!-- /.timeline-label -->
                        <!-- timeline item -->
                        <li>
                            <i class="fa fa-<?php print $build->getProject()->getIcon(); ?> bg-<?php print $color; ?>"></i>
                            <div class="timeline-item">
                                <span class="time"><i class="fa fa-clock-o"></i>
                                <?php
                                    echo $updated->format('H:i:s');
                                    if ($build->getStatus() != Build::STATUS_PENDING) {
                                        echo ' &mdash; ' . $build->getDuration(); ?> <?= Lang::get('seconds');
                                    }
                                ?>
                                </span>
                                <h3 class="timeline-header">
                                    <a href="<?php print APP_URL; ?>project/view/<?php print $build->getProjectId(); ?>">
                                        <?php print $build->getProject()->getTitle(); ?>
                                    </a>
                                    <span><?php print $environment; ?></span>
                                    &mdash; 
                                    <a href="<?php print APP_URL; ?>build/view/<?php print $build->getId(); ?>">
                                        Build #<?php print $build->getId(); ?>
                                    </a>
                                    &mdash; 
                                    <?php print $label; ?>
                                </h3>

                                <div class="timeline-body">
                                    <a href="<?= $build->getBranchLink();?>"><i class="fa fa-code-fork"></i> <?php echo $build->getBranch(); ?></a>
                                    <?= $branches ? ' + '.implode(', ', $branches) : ''; ?>
                                    <?php if ($tag = $build->getTag()): ?> / 
                                        <a href="<?= $build->getTagLink(); ?>" target="_blank">
                                            <i class="fa fa-tag"></i> <?= $tag; ?>
                                        </a>
                                    <?php endif; ?>
                                    &mdash; 
                                    <?php
                                    if ($build->getCommitId() !== 'Manual') {
                                        print sprintf(
                                            '<a href="%s" target="_blank">%s (%s)</a>',
                                            $build->getCommitLink(),
                                            substr($build->getCommitId(), 0, 7),
                                            $build->getCommitterEmail()
                                        );
                                    } else {
                                        print Lang::get('manual_build');
                                    }
                                    ?>
                                    &mdash; 
                                    <?php print $build->getCommitMessage(); ?>
                                </div>
                            </div>
                        </li>
                        <!-- END timeline item -->

                    <?php endforeach; ?>

                    <li>
                        <i class="fa fa-clock-o"></i>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</div>
