<?php

/**
 * @var array $widgets
 */

$all_widgets = array_merge(array_keys($widgets['left']), array_keys($widgets['right']));
foreach($all_widgets as $widget) {
    ?><script src="<?= APP_URL ?>assets/js/dashboard-widgets/<?= $widget ?>.js" type="text/javascript"></script><?php
}
?>
<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-5">
        <?php foreach ($widgets['left'] as $widget => $params) { ?>
            <div id="widget-<?= $widget ?>-container">
                <div class="loader"></div>
            </div>
        <?php } ?>
    </div>
<?php if (!empty($widgets['right'])) { ?>
    <div class="col-md-6 col-lg-7 pull-left">
        <?php foreach ($widgets['right'] as $widget => $params) { ?>
            <div id="widget-<?= $widget ?>-container">
                <div class="loader"></div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
</div>
