<?php

use PHPCensor\Helper\Lang;
use PHPCensor\Model\User;

/**
 * @var array $secrets
 * @var User  $user
 */

?>
<div class="clearfix"  style="margin-bottom: 20px;">
    <a class="btn btn-success pull-right" href="<?= (APP_URL . 'secret/edit'); ?>">
        <?= Lang::get('secret_add'); ?>
    </a>
</div>

<div class="box">
    <table class="table table-hover">
        <thead>
        <tr>
            <th><?= Lang::get('secret_name'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($secrets as $secret): ?>
            <tr>
                <td><?= $secret['name']; ?></td>
                <td>
                    <div class="btn-group btn-group-right">
                        <a class="btn btn-default btn-sm" href="<?= APP_URL; ?>secret/edit/<?= $secret['id']; ?>"><?= Lang::get('secret_edit'); ?></a>
                        <?php if ($user->getIsAdmin()): ?>
                            <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="<?= APP_URL; ?>secret/delete/<?= $secret['id']; ?>" class="delete-secret"><?= Lang::get('secret_delete'); ?></a></li>
                            </ul>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
        $('.delete-secret').on('click', function (e) {
            e.preventDefault();
            confirmDelete(e.target.href).onCloseConfirmed = function () {window.location = window.location.href};
        });
    });
</script>
